### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [mamamarina/kinozal-template#1]
1)
обрывы полей недопустимы, прошу исправить
![image](https://user-images.githubusercontent.com/8464662/101127104-7a541800-3605-11eb-90c6-41d56dd4ba68.png)

**Comment by mamamarina** [comment]
https://github.com/mamamarina/kinozal-template.git
https://mamamarina.github.io/kinozal-template/

**Comment by Alecto** [comment]
неправильное решение
![image](https://user-images.githubusercontent.com/8464662/101152946-6cfe5400-362c-11eb-9ee5-85e2ac51b517.png)

**Comment by mamamarina** [comment]
Переделала:
https://github.com/mamamarina/kinozal-template.git
https://mamamarina.github.io/kinozal-template/

**Comment by Alecto** [comment]
да, так лучше.
работа принята )

пт, 4 груд. 2020 о 13:05 Maryna Tuboleva <notifications@github.com> пише:

> Переделала:
> https://github.com/mamamarina/kinozal-template.git
> https://mamamarina.github.io/kinozal-template/
>

**Comment by Alecto** [comment]
напомните группу и фамилию, а то из письма непонятно )

сб, 5 груд. 2020 о 08:11 Андрей Фоменко <fomenkoandrey1978@gmail.com> пише:

> да, так лучше.
> работа принята )
>
> пт, 4 груд. 2020 о 13:05 Maryna Tuboleva <notifications@github.com> пише:
>
>> Переделала:
>> https://github.com/mamamarina/kinozal-template.git
>> https://mamamarina.github.io/kinozal-template/
>>

**Comment by mamamarina** [comment]
Ура!)Я была в группе выходного дня с 12 до 14, перешла вгруппу вт-чт
19.15-21.15 (коронавирус заставил:().

**Comment by Alecto** [comment]
отметил

сб, 5 груд. 2020 о 08:43 Maryna Tuboleva <notifications@github.com> пише:

> Ура!)Я была в группе выходного дня с 12 до 14, перешла вгруппу вт-чт
> 19.15-21.15 (коронавирус заставил:().
>
